# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'exisoGUI4LinuxUI.ui'
#
# Created: Sun Nov  8 13:09:49 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(640, 478)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.Localtab = QtGui.QWidget()
        self.Localtab.setObjectName(_fromUtf8("Localtab"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.Localtab)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label = QtGui.QLabel(self.Localtab)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        spacerItem = QtGui.QSpacerItem(318, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.Skip_Syst_Upd_checkBox = QtGui.QCheckBox(self.Localtab)
        self.Skip_Syst_Upd_checkBox.setChecked(True)
        self.Skip_Syst_Upd_checkBox.setObjectName(_fromUtf8("Skip_Syst_Upd_checkBox"))
        self.horizontalLayout_2.addWidget(self.Skip_Syst_Upd_checkBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.Local_Games_tableWidget = QtGui.QTableWidget(self.Localtab)
        self.Local_Games_tableWidget.setObjectName(_fromUtf8("Local_Games_tableWidget"))
        self.Local_Games_tableWidget.setColumnCount(3)
        self.Local_Games_tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.Local_Games_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.Local_Games_tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.Local_Games_tableWidget.setHorizontalHeaderItem(2, item)
        self.verticalLayout_2.addWidget(self.Local_Games_tableWidget)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.Add_ISO_pushButton = QtGui.QPushButton(self.Localtab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(191)
        sizePolicy.setVerticalStretch(24)
        sizePolicy.setHeightForWidth(self.Add_ISO_pushButton.sizePolicy().hasHeightForWidth())
        self.Add_ISO_pushButton.setSizePolicy(sizePolicy)
        self.Add_ISO_pushButton.setObjectName(_fromUtf8("Add_ISO_pushButton"))
        self.horizontalLayout_3.addWidget(self.Add_ISO_pushButton)
        self.Add_ISO_Folder_pushButton = QtGui.QPushButton(self.Localtab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(191)
        sizePolicy.setVerticalStretch(24)
        sizePolicy.setHeightForWidth(self.Add_ISO_Folder_pushButton.sizePolicy().hasHeightForWidth())
        self.Add_ISO_Folder_pushButton.setSizePolicy(sizePolicy)
        self.Add_ISO_Folder_pushButton.setObjectName(_fromUtf8("Add_ISO_Folder_pushButton"))
        self.horizontalLayout_3.addWidget(self.Add_ISO_Folder_pushButton)
        self.Remove_ISO_pushButton = QtGui.QPushButton(self.Localtab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(191)
        sizePolicy.setVerticalStretch(24)
        sizePolicy.setHeightForWidth(self.Remove_ISO_pushButton.sizePolicy().hasHeightForWidth())
        self.Remove_ISO_pushButton.setSizePolicy(sizePolicy)
        self.Remove_ISO_pushButton.setObjectName(_fromUtf8("Remove_ISO_pushButton"))
        self.horizontalLayout_3.addWidget(self.Remove_ISO_pushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_3 = QtGui.QLabel(self.Localtab)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_4.addWidget(self.label_3)
        self.Tot_proc_progressBar = QtGui.QProgressBar(self.Localtab)
        self.Tot_proc_progressBar.setProperty("value", 0)
        self.Tot_proc_progressBar.setObjectName(_fromUtf8("Tot_proc_progressBar"))
        self.horizontalLayout_4.addWidget(self.Tot_proc_progressBar)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_4 = QtGui.QLabel(self.Localtab)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_5.addWidget(self.label_4)
        self.Curr_File_progressBar = QtGui.QProgressBar(self.Localtab)
        self.Curr_File_progressBar.setProperty("value", 0)
        self.Curr_File_progressBar.setObjectName(_fromUtf8("Curr_File_progressBar"))
        self.horizontalLayout_5.addWidget(self.Curr_File_progressBar)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.Logs_checkBox = QtGui.QCheckBox(self.Localtab)
        self.Logs_checkBox.setChecked(True)
        self.Logs_checkBox.setObjectName(_fromUtf8("Logs_checkBox"))
        self.horizontalLayout_6.addWidget(self.Logs_checkBox)
        spacerItem1 = QtGui.QSpacerItem(478, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.Logs_listView = QtGui.QListView(self.Localtab)
        self.Logs_listView.setObjectName(_fromUtf8("Logs_listView"))
        self.verticalLayout_2.addWidget(self.Logs_listView)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        spacerItem2 = QtGui.QSpacerItem(198, 41, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.Start_pushButton = QtGui.QPushButton(self.Localtab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(40)
        sizePolicy.setVerticalStretch(41)
        sizePolicy.setHeightForWidth(self.Start_pushButton.sizePolicy().hasHeightForWidth())
        self.Start_pushButton.setSizePolicy(sizePolicy)
        self.Start_pushButton.setObjectName(_fromUtf8("Start_pushButton"))
        self.horizontalLayout_7.addWidget(self.Start_pushButton)
        spacerItem3 = QtGui.QSpacerItem(208, 41, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.tabWidget.addTab(self.Localtab, _fromUtf8(""))
        self.FTPtab = QtGui.QWidget()
        self.FTPtab.setObjectName(_fromUtf8("FTPtab"))
        self.tabWidget.addTab(self.FTPtab, _fromUtf8(""))
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionAdd = QtGui.QAction(MainWindow)
        self.actionAdd.setObjectName(_fromUtf8("actionAdd"))
        self.actionRemove = QtGui.QAction(MainWindow)
        self.actionRemove.setObjectName(_fromUtf8("actionRemove"))
        self.actionAdd_ISO_File = QtGui.QAction(MainWindow)
        self.actionAdd_ISO_File.setObjectName(_fromUtf8("actionAdd_ISO_File"))
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionSoftware_Help = QtGui.QAction(MainWindow)
        self.actionSoftware_Help.setObjectName(_fromUtf8("actionSoftware_Help"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.menuFile.addAction(self.actionAdd)
        self.menuFile.addAction(self.actionAdd_ISO_File)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionRemove)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionSoftware_Help)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "ExisoGUI4Linux v0.1", None))
        self.label.setText(_translate("MainWindow", "ISOs list:", None))
        self.Skip_Syst_Upd_checkBox.setText(_translate("MainWindow", "Skip $SystemUpdate folder", None))
        item = self.Local_Games_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Type", None))
        item = self.Local_Games_tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Image Source", None))
        item = self.Local_Games_tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Destination", None))
        self.Add_ISO_pushButton.setText(_translate("MainWindow", "Add an ISO", None))
        self.Add_ISO_Folder_pushButton.setText(_translate("MainWindow", "Add an ISO Folder", None))
        self.Remove_ISO_pushButton.setText(_translate("MainWindow", "Remove selected ISO from list", None))
        self.label_3.setText(_translate("MainWindow", "Total process:", None))
        self.label_4.setText(_translate("MainWindow", "Current File:   ", None))
        self.Logs_checkBox.setText(_translate("MainWindow", "Logs:", None))
        self.Start_pushButton.setText(_translate("MainWindow", "Start", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Localtab), _translate("MainWindow", "Local", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.FTPtab), _translate("MainWindow", "FTP", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.actionAdd.setText(_translate("MainWindow", "Add ISO", None))
        self.actionRemove.setText(_translate("MainWindow", "Remove ISO", None))
        self.actionAdd_ISO_File.setText(_translate("MainWindow", "Add ISO Folder", None))
        self.actionQuit.setText(_translate("MainWindow", "Quit", None))
        self.actionSoftware_Help.setText(_translate("MainWindow", "Software Help", None))
        self.actionAbout.setText(_translate("MainWindow", "About", None))

